class AdventureGear:
    def __init__  (self, name, cost, weight):
        self.name = name
        self.cost = cost
        self.weight = weight
    def __str__ (self):
        return f'Name: {self.name} \nCost: {self.cost} \nWeight: {self.weight}'

adventuregear = {
    'abacus': AdventureGear('Abacus', '2 gp', '2 lb'),
    'acid': AdventureGear("Acid (vial)", '25 gp', '1 lb'),
    'alchemist fire': AdventureGear("Alchemist's Fire (flask)", '50 gp', '1 lb'),
    'arrows': AdventureGear("Arrows (20)", '1 gp', '1 lb'),
    'antitoxin': AdventureGear("Antitoxin (vial)", '50 gp', '—'),
    'arcane focus': AdventureGear("Arcane Focus", '5-50 gp', '1 lb'),
    'backpack': AdventureGear('Backpack', '2 gp', '5 lb'),
    'ball bearings': AdventureGear('Ball Bearings (bag of 1,000)', '1 gp', '2 lb'),
    'barrel': AdventureGear('Barrel', '2 gp', '70 lb'),
    'basket': AdventureGear('Basket', '4 sp', '2 lb'),
    'bedroll': AdventureGear('Bedroll', '1 gp', '7 lb'),
    'bell': AdventureGear('Bell', '1 gp', '—'),
    'blanket': AdventureGear('Blanket', '5 sp', '3 lb'),
    'block and tackle': AdventureGear('Block and Tackle', '1 gp', '5 lb'),
    'book': AdventureGear('Book', 'Varies', '5 lb'),
    'bottle glass': AdventureGear('Bottle, Glass (vial)', '2 gp', 'Varies'),
    'bucket': AdventureGear('Bucket', '5 sp', '2 lb'),
    'caltrops': AdventureGear('Caltrops (bag of 20)', '1 gp', '2 lb'),
    'candle': AdventureGear('Candle', '1 cp', 'Varies'),
    'case crossbow bolt': AdventureGear('Case, Crossbow Bolt', '1 gp', '1 lb'),
    'case map scroll': AdventureGear('Case, Map or Scroll', '1 gp', '1 lb'),
    'chain': AdventureGear('Chain (10 feet)', '5 gp', '10 lb'),
    'chalk': AdventureGear('Chalk (1 piece)', '1 cp', '—'),
    'chest': AdventureGear('Chest', '5 gp', '25 lb'),
    'climbers kit': AdventureGear("Climber's Kit", '25 gp', '12 lb'),
    'clothes common': AdventureGear('Clothes, Common', '5 sp', 'Varies'),
    'clothes costume': AdventureGear('Clothes, Costume', '5 gp', 'Varies'),
    'clothes fine': AdventureGear('Clothes, Fine', '15 gp', 'Varies'),
    'clothes travelers': AdventureGear('Clothes, Traveler’s', '2 gp', 'Varies'),
    'component pouch': AdventureGear('Component Pouch', '25 gp', '2 lb'),
    'crowbar': AdventureGear('Crowbar', '2 gp', '5 lb'),
    'fishing tackle': AdventureGear('Fishing Tackle', '1 gp', '4 lb'),
    'flask tankard': AdventureGear('Flask or Tankard', '2 cp', '1 lb'),
    'flint and steel': AdventureGear('Flint and Steel', '1 gp', '—'),
    'forgery kit': AdventureGear('Forgery Kit', '15 gp', '5 lb'),
    'glassblowers tools': AdventureGear('Glassblower’s Tools', '30 gp', '5 lb'),
    'grappling hook': AdventureGear('Grappling Hook', '2 gp', '4 lb'),
    'hammer': AdventureGear('Hammer', '1 gp', '3 lb'),
    'sledge hammer': AdventureGear('Hammer, Sledge', '2 gp', '10 lb'),
    'healers kit': AdventureGear("Healer's Kit", '5 gp', '3 lb'),
    'holy symbol': AdventureGear('Holy Symbol', '5-25 gp', '1 lb'),
    'hourglass': AdventureGear('Hourglass', '25 gp', '1 lb'),
    'hunting trap': AdventureGear('Hunting Trap', '5 gp', '25 lb'),
    'ink': AdventureGear('Ink (1 ounce bottle)', '10 gp', '—'),
    'ink pen': AdventureGear('Ink Pen', '2 cp', '—'),
    'jug pitcher': AdventureGear('Jug or Pitcher', '2 cp', '4 lb'),
    'ladder': AdventureGear('Ladder (10-foot)', '1 sp', '25 lb'),
    'lamp': AdventureGear('Lamp', '5 sp', '1 lb'),
    'lantern bullseye': AdventureGear('Lantern, Bullseye', '10 gp', '2 lb'),
    'lantern hooded': AdventureGear('Lantern, Hooded', '5 gp', '2 lb'),
    'lock': AdventureGear('Lock', '10 gp', '1 lb'),
    'magnifying glass': AdventureGear('Magnifying Glass', '100 gp', '—'),
    'manacles': AdventureGear('Manacles', '2 gp', '6 lb'),
    'mess kit': AdventureGear('Mess Kit', '2 sp', '1 lb'),
    'mirror steel': AdventureGear('Mirror, Steel', '5 gp', '0.5 lb'),
    'oil': AdventureGear('Oil (flask)', '1 sp', '1 lb'),
    'paper': AdventureGear('Paper (one sheet)', '2 sp', '—'),
    'parchment': AdventureGear('Parchment (one sheet)', '1 sp', '—'),
    'perfume': AdventureGear('Perfume (vial)', '5 gp', '—'),
    'pick miners': AdventureGear("Pick, Miner's", '2 gp', '10 lb'),
    'piton': AdventureGear('Piton', '5 cp', '0.25 lb'),
    'poisoners kit': AdventureGear("Poisoner's Kit", '50 gp', '2 lb'),
    'pole': AdventureGear('Pole (10-foot)', '5 cp', '7 lb'),
    'iron pot': AdventureGear('Pot, Iron', '2 gp', '10 lb'),
    'potion of healing': AdventureGear('Potion of Healing', '50 gp', 'Varies'),
    'pouch': AdventureGear('Pouch', '5 sp', '1 lb'),
    'quiver': AdventureGear('Quiver', '1 gp', '1 lb'),
    'ram portable': AdventureGear('Ram, Portable', '4 gp', '35 lb'),
    'rations': AdventureGear('Rations (1 day)', '5 sp', '2 lb'),
    'robes': AdventureGear('Robes', '1 gp', '4 lb'),
    'rope hempen': AdventureGear('Rope, Hempen (50 feet)', '1 gp', '10 lb'),
    'rope silk': AdventureGear('Rope, Silk (50 feet)', '10 gp', '5 lb'),
    'sack': AdventureGear('Sack', '1 cp', '0.5 lb'),
    'scale merchants': AdventureGear("Scale, Merchant's", '5 gp', '3 lb'),
    'sealing wax': AdventureGear('Sealing Wax', '1 gp', '—'),
    'shovel': AdventureGear('Shovel', '2 gp', '5 lb'),
    'signal whistle': AdventureGear('Signal Whistle', '5 cp', '—'),
    'signet ring': AdventureGear('Signet Ring', '5 gp', '—'),
    'soap': AdventureGear('Soap', '2 cp', '—'),
    'spellbook': AdventureGear('Spellbook', 'Varies', '3 lb'),
    'spikes iron': AdventureGear('Spikes, Iron (10)', '5 cp', '5 lb'),
    'spyglass': AdventureGear('Spyglass', '1,000 gp', '1 lb'),
    'tent two person': AdventureGear('Tent, Two-Person', '2 gp', '20 lb'),
    'tinderbox': AdventureGear('Tinderbox', '5 sp', '1 lb'),
    'torch': AdventureGear('Torch', '1 cp', '1 lb'),
    'vial': AdventureGear('Vial', '1 gp', '—'),
    'waterskin': AdventureGear('Waterskin', '2 sp', '5 lb'),
    'whetstone': AdventureGear('Whetstone', '1 cp', '1 lb')
}